// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hthusloogpnfqefzskvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0aHVzbG9vZ3BuZnFlZnpza3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODc2NDcsImV4cCI6MjA2NTY2MzY0N30.soGYOMP7fAb9hb5lxfkWfnbK2qCfwh8QKQVVzLi6qbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);